name: "Distribution support request"
description: "Request a new distribution"
title: "[Distribution]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        You may request a distribution that is not present in `proot-distro list`. Please note that non-standard distributions like "Gentoo Prefix" as well as distributions that assist hacking will be rejected.
  - type: textarea
    attributes:
      label: Description
      description: 
  - type: input
    attributes:
      label: Home page URL
    validations:
      required: true
  - type: input
    attributes:
      label: Root file system archive URL
  - type: checkboxes
    attributes:
      label: Is requested distribution has support for AArch64 (ARM64) and ARM CPUs?
      description: Distributions not supporting at least AArch64 and ARM devices are not eligible for PRoot Distro support. Please provide the true answer as otherwise issue will be closed without feedback.
      options:
        - label: Yes, distribution supports AArch64 and ARM.
          required: true
