name: "Distribution support request"
description: "Request a new distribution"
title: "[Distribution]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        You can check supported distributions by running command `proot-distro list`. If you have not found the desired one, you can request it.

        Requests of distributions that assist hacking will be rejected without feedback.
  - type: textarea
    attributes:
      label: Description
      description: 
  - type: input
    attributes:
      label: Home page URL
    validations:
      required: true
  - type: input
    attributes:
      label: Root file system archive URL
